// packages/slideyui-svelte/src/lib/components/Presentation.svelte
<script lang="ts">
  /**
   * Presentation Component
   * Full-screen card presentation wrapper
   * Replaces Deck with modern card-centric approach
   *
   * @example
   * ```svelte
   * <Presentation theme="corporate" showProgress cards={[card1, card2, card3]}>
   *   <!-- Or use default slot with manual card management -->
   * </Presentation>
   * ```
   */

  import { setPresentationContext, presentationKeyboard } from '../stores/presentation';
  import PresentationProgress from './PresentationProgress.svelte';
  import PresentationNumber from './PresentationNumber.svelte';
  import PresentationControls from './PresentationControls.svelte';
  import type { SlideTheme } from '../types';
  import { onMount } from 'svelte';

  /**
   * Presentation theme
   * @default 'minimal'
   */
  export let theme: SlideTheme = 'minimal';

  /**
   * Initial card index
   * @default 0
   */
  export let initialCard: number = 0;

  /**
   * Enable keyboard navigation
   * @default true
   */
  export let enableKeyboard: boolean = true;

  /**
   * Show progress indicator
   * @default false
   */
  export let showProgress: boolean = false;

  /**
   * Progress indicator position
   * @default 'bottom'
   */
  export let progressPosition: 'top' | 'bottom' = 'bottom';

  /**
   * Show card numbers
   * @default false
   */
  export let showCardNumbers: boolean = false;

  /**
   * Card number position
   * @default 'bottom-right'
   */
  export let cardNumberPosition: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left' =
    'bottom-right';

  /**
   * Enable presenter mode (speaker notes, controls)
   * @default false
   */
  export let presenterMode: boolean = false;

  /**
   * Callback when card changes
   */
  export let onCardChange: ((cardIndex: number) => void) | undefined = undefined;

  /**
   * Additional CSS classes
   */
  let className = '';
  export { className as class };

  // Track children container
  let containerElement: HTMLDivElement;
  let totalCards = 0;

  // Create presentation context
  const presentation = setPresentationContext(
    {
      currentCard: initialCard,
      totalCards: 0,
      theme,
      presenterMode,
      isPresentationMode: true,
    },
    onCardChange
  );

  // Count children on mount and when they change
  function updateCardCount() {
    if (containerElement) {
      const children = containerElement.children;
      totalCards = children.length;

      // Update the store's total cards
      presentation.setTotalCards(totalCards);

      // Ensure current card is within bounds
      if ($presentation.currentCard >= totalCards) {
        presentation.goToCard(Math.max(0, totalCards - 1));
      }
    }
  }

  onMount(() => {
    updateCardCount();

    // Watch for DOM changes (in case cards are added/removed dynamically)
    const observer = new MutationObserver(updateCardCount);
    if (containerElement) {
      observer.observe(containerElement, { childList: true });
    }

    return () => observer.disconnect();
  });

  // Reactive style for showing only current card
  $: currentCardStyle = `--current-card: ${$presentation.currentCard}`;
</script>

<!--
  Full-screen card presentation wrapper
  Manages card navigation, progress, and presenter controls
-->
<div
  class="presentation-container fixed inset-0 w-screen h-screen overflow-hidden theme-{theme} {className}"
  data-theme={theme}
  use:presentationKeyboard={enableKeyboard ? presentation : undefined}
  style={currentCardStyle}
>
  <!-- Full-screen card container -->
  <div class="w-full h-full flex items-center justify-center p-8">
    <div
      bind:this={containerElement}
      class="presentation-cards w-full max-w-[90vw] max-h-[90vh]"
    >
      <slot />
    </div>
  </div>

  <!-- Progress indicator -->
  {#if showProgress}
    <PresentationProgress position={progressPosition} />
  {/if}

  <!-- Card numbers -->
  {#if showCardNumbers}
    <PresentationNumber position={cardNumberPosition} />
  {/if}

  <!-- Presenter controls -->
  <PresentationControls />
</div>

<style>
  /* Hide all cards by default */
  .presentation-cards :global(> *) {
    display: none;
    width: 100%;
    height: 100%;
  }

  /* Show only the current card using CSS counter */
  .presentation-cards :global(> *:nth-child(calc(var(--current-card) + 1))) {
    display: flex;
    flex-direction: column;
  }
</style>

// packages/slideyui-react/src/components/Presentation.tsx
/**
 * Presentation Component
 * Wrapper for full-screen card presentations
 * Replaces Deck with modern card-centric approach
 */

import { Children, ReactElement, cloneElement, isValidElement } from 'react';
import { PresentationProps } from '../types';
import { PresentationProvider, usePresentationKeyboard } from '../context/PresentationContext';
import clsx from 'clsx';

/**
 * Progress indicator component
 */
function PresentationProgress({ position = 'bottom' }: { position?: 'top' | 'bottom' }) {
  const { currentCard, totalCards } = usePresentationContext();
  const progress = totalCards > 0 ? ((currentCard + 1) / totalCards) * 100 : 0;

  return (
    <div
      className={clsx(
        'slide-progress fixed left-0 right-0 z-50',
        position === 'top' ? 'top-0' : 'bottom-0'
      )}
    >
      <div className="slide-progress-bar" style={{ width: `${progress}%` }} />
    </div>
  );
}

/**
 * Card number indicator
 */
function PresentationNumber({ position = 'bottom-right' }: { position?: string }) {
  const { currentCard, totalCards } = usePresentationContext();

  const positionClasses: Record<string, string> = {
    'bottom-right': 'bottom-4 right-4',
    'bottom-left': 'bottom-4 left-4',
    'top-right': 'top-4 right-4',
    'top-left': 'top-4 left-4',
  };

  return (
    <div className={clsx('slide-number fixed z-50', positionClasses[position])}>
      {currentCard + 1} / {totalCards}
    </div>
  );
}

/**
 * Presentation controls overlay
 */
function PresentationControls() {
  const { currentCard, totalCards, nextCard, previousCard, presenterMode } =
    usePresentationContext();

  if (!presenterMode) return null;

  return (
    <div className="fixed bottom-8 left-1/2 -translate-x-1/2 z-50">
      <div className="flex items-center gap-4 bg-base-100/95 backdrop-blur rounded-full px-6 py-3 shadow-xl border border-base-300">
        <button
          onClick={previousCard}
          disabled={currentCard === 0}
          className="btn btn-circle btn-sm btn-ghost"
          aria-label="Previous card"
        >
          ←
        </button>

        <div className="text-sm font-medium">
          {currentCard + 1} / {totalCards}
        </div>

        <button
          onClick={nextCard}
          disabled={currentCard >= totalCards - 1}
          className="btn btn-circle btn-sm btn-ghost"
          aria-label="Next card"
        >
          →
        </button>
      </div>
    </div>
  );
}

/**
 * Internal presentation view component
 */
function PresentationView({
  children,
  theme = 'minimal',
  className = '',
  showProgress = false,
  progressPosition = 'bottom',
  showCardNumbers = false,
  cardNumberPosition = 'bottom-right',
}: Omit<PresentationProps, 'initialCard' | 'onCardChange' | 'enableKeyboard' | 'presenterMode'>) {
  const { currentCard } = usePresentationContext();

  // Enable keyboard navigation
  usePresentationKeyboard();

  // Convert children to array
  const cards = Children.toArray(children).filter(isValidElement);

  // Get current card
  const currentCardElement = cards[currentCard];

  return (
    <div
      className={clsx(
        'presentation-container',
        'fixed inset-0 w-screen h-screen overflow-hidden',
        `theme-${theme}`,
        className
      )}
      data-theme={theme}
    >
      {/* Full-screen card */}
      <div className="w-full h-full flex items-center justify-center p-8">
        {currentCardElement &&
          cloneElement(currentCardElement as ReactElement, {
            // Force full mode for presentation
            mode: 'full',
            aspectRatio: '16/9',
            className: clsx(
              (currentCardElement as ReactElement).props.className,
              'w-full max-w-[90vw] max-h-[90vh]'
            ),
          })}
      </div>

      {/* Progress indicator */}
      {showProgress && <PresentationProgress position={progressPosition} />}

      {/* Card numbers */}
      {showCardNumbers && <PresentationNumber position={cardNumberPosition} />}

      {/* Presenter controls */}
      <PresentationControls />
    </div>
  );
}

/**
 * Full-screen card presentation wrapper
 *
 * @example
 * ```tsx
 * <Presentation theme="corporate" showProgress>
 *   <ContentCard title="Welcome">
 *     <p>First card</p>
 *   </ContentCard>
 *   <DataCard title="Metrics">
 *     <Chart />
 *   </DataCard>
 * </Presentation>
 * ```
 */
export function Presentation({
  children,
  theme = 'minimal',
  initialCard = 0,
  enableKeyboard = true,
  onCardChange,
  presenterMode = false,
  ...viewProps
}: PresentationProps) {
  const cards = Children.toArray(children);
  const totalCards = cards.length;

  return (
    <PresentationProvider
      theme={theme}
      initialCard={initialCard}
      totalCards={totalCards}
      onCardChange={onCardChange}
      enablePresenterMode={presenterMode}
    >
      <PresentationView theme={theme} {...viewProps}>
        {children}
      </PresentationView>
    </PresentationProvider>
  );
}

// Re-export context hook
import { usePresentationContext } from '../context/PresentationContext';
export { usePresentationContext };
