// packages/slideyui-svelte/src/lib/components/Timeline.svelte
<!--
  Timeline Component
  Timeline visualization for chronological events
-->

<script lang="ts">
  import type { TimelineEvent } from '../types';

  /**
   * Timeline events
   */
  export let events: TimelineEvent[];

  /**
   * Timeline orientation
   */
  export let orientation: 'vertical' | 'horizontal' = 'vertical';

  /**
   * Timeline variant
   */
  export let variant: 'default' | 'minimal' | 'detailed' = 'default';

  /**
   * Additional CSS classes
   */
  let className: string = '';
  export { className as class };
</script>

<!--
  Timeline component for displaying chronological events

  @example
  ```svelte
  <Timeline
    orientation="vertical"
    variant="detailed"
    events={[
      { title: '2020', description: 'Company founded', date: 'Jan 2020' },
      { title: '2021', description: 'Series A funding', date: 'Mar 2021' },
      { title: '2022', description: 'Product launch', date: 'Jun 2022' },
    ]}
  />
  ```
-->

<div
  class="slide-timeline slide-timeline-{orientation} slide-timeline-{variant} {className}"
>
  {#each events as event, index}
    <div class="slide-timeline-item">
      <div class="slide-timeline-marker">
        <div class="slide-timeline-dot" />
      </div>

      <div class="slide-timeline-content">
        {#if event.date}
          <div class="slide-timeline-date">{event.date}</div>
        {/if}
        <h4 class="slide-timeline-title">{event.title}</h4>
        {#if event.description}
          <p class="slide-timeline-description">{event.description}</p>
        {/if}
      </div>

      {#if index < events.length - 1}
        <div class="slide-timeline-connector" />
      {/if}
    </div>
  {/each}
</div>

// packages/slideyui-react/src/components/Timeline.tsx
/**
 * Timeline Component
 * Timeline visualization for chronological events
 */

import { SlideTimelineProps } from '../types';

/**
 * Timeline component for displaying chronological events
 *
 * @example
 * ```tsx
 * <Timeline
 *   orientation="vertical"
 *   variant="detailed"
 *   events={[
 *     { title: '2020', description: 'Company founded', date: 'Jan 2020' },
 *     { title: '2021', description: 'Series A funding', date: 'Mar 2021' },
 *     { title: '2022', description: 'Product launch', date: 'Jun 2022' },
 *   ]}
 * />
 * ```
 */
export function Timeline({
  events,
  orientation = 'vertical',
  variant = 'default',
  className = '',
}: SlideTimelineProps) {
  return (
    <div
      className={`slide-timeline slide-timeline-${orientation} slide-timeline-${variant} ${className}`}
    >
      {events.map((event, index) => (
        <div key={index} className="slide-timeline-item">
          <div className="slide-timeline-marker">
            {event.icon ? (
              <div className="slide-timeline-icon">{event.icon}</div>
            ) : (
              <div className="slide-timeline-dot" />
            )}
          </div>

          <div className="slide-timeline-content">
            {event.date && (
              <div className="slide-timeline-date">{event.date}</div>
            )}
            <h4 className="slide-timeline-title">{event.title}</h4>
            {event.description && (
              <p className="slide-timeline-description">{event.description}</p>
            )}
          </div>

          {index < events.length - 1 && (
            <div className="slide-timeline-connector" />
          )}
        </div>
      ))}
    </div>
  );
}
