// packages/slideyui-react/src/components/Callout.tsx
/**
 * Callout Component
 * Highlighted callout box for important information
 */

import { ReactNode } from 'react';
import { SlideCalloutProps } from '../types';

/**
 * Default icons for each callout type
 */
const defaultIcons: Record<string, ReactNode> = {
  info: (
    <svg className="slide-callout-icon" fill="currentColor" viewBox="0 0 20 20">
      <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
    </svg>
  ),
  key: (
    <svg className="slide-callout-icon" fill="currentColor" viewBox="0 0 20 20">
      <path fillRule="evenodd" d="M18 8a6 6 0 01-7.743 5.743L10 14l-1 1-1 1H6v2H2v-4l4.257-4.257A6 6 0 1118 8zm-6-4a1 1 0 100 2 2 2 0 012 2 1 1 0 102 0 4 4 0 00-4-4z" clipRule="evenodd" />
    </svg>
  ),
  warning: (
    <svg className="slide-callout-icon" fill="currentColor" viewBox="0 0 20 20">
      <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
    </svg>
  ),
  success: (
    <svg className="slide-callout-icon" fill="currentColor" viewBox="0 0 20 20">
      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
    </svg>
  ),
  question: (
    <svg className="slide-callout-icon" fill="currentColor" viewBox="0 0 20 20">
      <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clipRule="evenodd" />
    </svg>
  ),
};

/**
 * Callout box component for highlighting important information
 *
 * @example
 * ```tsx
 * <Callout type="warning" title="Important Note">
 *   This feature requires administrator access.
 * </Callout>
 *
 * <Callout type="key">
 *   Remember this key concept for the exam.
 * </Callout>
 * ```
 */
export function Callout({
  type = 'info',
  title,
  icon,
  className = '',
  children,
}: SlideCalloutProps) {
  const calloutIcon = icon || defaultIcons[type];

  return (
    <div className={`slide-callout slide-callout-${type} ${className}`}>
      <div className="slide-callout-header">
        {calloutIcon && (
          <div className="slide-callout-icon-wrapper">
            {calloutIcon}
          </div>
        )}
        {title && (
          <h4 className="slide-callout-title">{title}</h4>
        )}
      </div>
      <div className="slide-callout-body">
        {children}
      </div>
    </div>
  );
}

// packages/slideyui-svelte/src/lib/components/Callout.svelte
<!--
  Callout Component
  Highlighted callout box for important information
-->

<script lang="ts">
  import type { Snippet } from 'svelte';

  /**
   * Callout type
   */
  export let type: 'info' | 'key' | 'warning' | 'success' | 'question' = 'info';

  /**
   * Callout title
   */
  export let title: string | undefined = undefined;

  /**
   * Additional CSS classes
   */
  let className: string = '';
  export { className as class };

  /**
   * Icon slot for custom icons
   */
  export let icon: Snippet | undefined = undefined;

  /**
   * Default content slot
   */
  export let children: Snippet | undefined = undefined;
</script>

<!--
  Callout box component for highlighting important information

  @example
  ```svelte
  <Callout type="warning" title="Important Note">
    This feature requires administrator access.
  </Callout>

  <Callout type="key">
    Remember this key concept for the exam.
  </Callout>
  ```
-->

<div class="slide-callout slide-callout-{type} {className}">
  <div class="slide-callout-header">
    {#if icon}
      <div class="slide-callout-icon-wrapper">
        {@render icon()}
      </div>
    {:else}
      <div class="slide-callout-icon-wrapper">
        {#if type === 'info'}
          <svg class="slide-callout-icon" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
          </svg>
        {:else if type === 'key'}
          <svg class="slide-callout-icon" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M18 8a6 6 0 01-7.743 5.743L10 14l-1 1-1 1H6v2H2v-4l4.257-4.257A6 6 0 1118 8zm-6-4a1 1 0 100 2 2 2 0 012 2 1 1 0 102 0 4 4 0 00-4-4z" clip-rule="evenodd" />
          </svg>
        {:else if type === 'warning'}
          <svg class="slide-callout-icon" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
          </svg>
        {:else if type === 'success'}
          <svg class="slide-callout-icon" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
          </svg>
        {:else if type === 'question'}
          <svg class="slide-callout-icon" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd" />
          </svg>
        {/if}
      </div>
    {/if}
    {#if title}
      <h4 class="slide-callout-title">{title}</h4>
    {/if}
  </div>
  <div class="slide-callout-body">
    {#if children}
      {@render children()}
    {/if}
  </div>
</div>
