// packages/slideyui-react/src/components/cards/ContentCard.tsx
/**
 * ContentCard Component
 * Text-heavy presentation card with header, body, and footer sections
 * Optimized for readability at presentation scale
 */

import { ContentCardProps } from '../../types';
import { CardContainer } from './CardContainer';
import clsx from 'clsx';

/**
 * Content-focused card for text-heavy slides
 *
 * @example
 * ```tsx
 * <ContentCard
 *   title="Key Features"
 *   subtitle="What makes us different"
 *   badge={<span className="card-badge">New</span>}
 *   footer={<p className="text-sm">Learn more →</p>}
 *   density="concise"
 *   padding="default"
 * >
 *   <ul className="card-list">
 *     <li>Feature 1</li>
 *     <li>Feature 2</li>
 *   </ul>
 * </ContentCard>
 * ```
 */
export function ContentCard({
  title,
  subtitle,
  children,
  badge,
  footer,
  icon,
  variant = 'default',
  density = 'detailed',
  padding = 'default',
  className = '',
  ...containerProps
}: ContentCardProps) {
  const paddingClass = {
    compact: 'slide-card-compact',
    default: '',
    spacious: 'slide-card-spacious',
    none: 'slide-card-flush',
  }[padding];

  return (
    <CardContainer {...containerProps} className={clsx('flex flex-col', paddingClass, className)}>
      {/* Header */}
      {(title || subtitle || badge || icon) && (
        <div className={clsx('slide-card-header', variant === 'featured' && 'bg-slidey-accent/10')}>
          <div className="flex items-start justify-between gap-4">
            <div className="flex items-start gap-3 flex-1">
              {icon && <div className="flex-shrink-0 mt-1">{icon}</div>}
              <div className="flex-1">
                {title && (
                  <h3
                    className={clsx(
                      'slide-card-title',
                      variant === 'minimal' && 'text-2xl font-normal'
                    )}
                  >
                    {title}
                  </h3>
                )}
                {subtitle && (
                  <p className="slide-card-description mt-1">{subtitle}</p>
                )}
              </div>
            </div>
            {badge && <div className="flex-shrink-0">{badge}</div>}
          </div>
        </div>
      )}

      {/* Body */}
      {children && (
        <div className={clsx('slide-card-body flex-1 overflow-auto', `slide-card-density-${density}`)}>
          {children}
        </div>
      )}

      {/* Footer */}
      {footer && (
        <div className="slide-card-footer">
          {footer}
        </div>
      )}
    </CardContainer>
  );
}

// packages/slideyui-svelte/src/lib/components/ContentCard.svelte
<script lang="ts">
	/**
	 * ContentCard Component
	 * Text-heavy presentation card with header, body, and footer sections
	 * Optimized for readability at presentation scale
	 */

	import CardContainer from './CardContainer.svelte';
	import type { CardPadding } from '../types';

	export let title: string | undefined = undefined;
	export let subtitle: string | undefined = undefined;
	export let variant: 'default' | 'featured' | 'minimal' = 'default';
	export let density: 'minimal' | 'concise' | 'detailed' | 'extensive' = 'detailed';
	export let padding: CardPadding = 'default';
	export let aspectRatio: '16/9' | '4/3' | '1/1' | '3/2' | 'auto' = '16/9';
	export let mode: 'preview' | 'thumbnail' | 'full' = 'preview';
	export let bordered: boolean = true;
	export let shadow: boolean = true;
	export let interactive: boolean = false;
	export let backgroundColor: string | undefined = undefined;
	export let backgroundImage: string | undefined = undefined;
	export let cardId: string | undefined = undefined;
	export let cardState: 'generating' | 'selected' | 'error' | 'complete' | undefined = undefined;

	let className: string = '';
	export { className as class };

	const paddingClass = {
		compact: 'slide-card-compact',
		default: '',
		spacious: 'slide-card-spacious',
		none: 'slide-card-flush',
	}[padding];

	$$restProps; // Allow passing through other props
</script>

<CardContainer
	{aspectRatio}
	{mode}
	{bordered}
	{shadow}
	{interactive}
	{backgroundColor}
	{backgroundImage}
	{cardId}
	{cardState}
	class="flex flex-col {paddingClass} {className}"
>
	{#if title || subtitle}
		<div class="slide-card-header {variant === 'featured' ? 'bg-slidey-accent/10' : ''}">
			<div class="flex items-start justify-between gap-4">
				<div class="flex items-start gap-3 flex-1">
					<slot name="icon" />
					<div class="flex-1">
						{#if title}
							<h3
								class="slide-card-title {variant === 'minimal' ? 'text-2xl font-normal' : ''}"
							>
								{title}
							</h3>
						{/if}
						{#if subtitle}
							<p class="slide-card-description mt-1">{subtitle}</p>
						{/if}
					</div>
				</div>
				<slot name="badge" />
			</div>
		</div>
	{/if}

	<div class="slide-card-body slide-card-density-{density} flex-1 overflow-auto">
		<slot />
	</div>

	<slot name="footer">
		<!-- Default footer slot -->
	</slot>
</CardContainer>
