// packages/slideyui-react/src/components/cards/MediaCard.tsx
/**
 * MediaCard Component
 * Image, video, and SVG-focused presentation card
 * Optimized for visual content with optional overlays and captions
 */

import { MediaCardProps } from '../../types';
import { CardContainer } from './CardContainer';
import clsx from 'clsx';
import { useState } from 'react';

const objectFitClasses: Record<string, string> = {
  cover: 'object-cover',
  contain: 'object-contain',
  fill: 'object-fill',
};

/**
 * Media-focused card for images, videos, and SVG graphics
 *
 * @example
 * ```tsx
 * // Image card with caption
 * <MediaCard
 *   src="/images/chart.png"
 *   alt="Sales growth chart"
 *   caption="Q4 Revenue: +42%"
 * />
 *
 * // SVG content (interactive mode)
 * <MediaCard
 *   mediaType="svg"
 *   svgContent="<svg>...</svg>"
 *   svgType="interactive"
 *   alt="Custom diagram"
 * />
 *
 * // SVG content (image mode with data URI)
 * <MediaCard
 *   mediaType="svg"
 *   svgContent="<svg>...</svg>"
 *   svgType="image"
 *   alt="Icon"
 * />
 *
 * // Background image with overlay content
 * <MediaCard
 *   src="/images/hero.jpg"
 *   asBackground
 *   overlay={<div className="bg-black/50 p-6 rounded-lg">...</div>}
 * >
 *   <h2 className="text-white text-4xl">Overlay Content</h2>
 * </MediaCard>
 *
 * // Image with error fallback
 * <MediaCard
 *   src="/images/might-fail.jpg"
 *   fallbackImage="/images/placeholder.jpg"
 *   onError={(err) => console.error('Failed to load:', err)}
 * />
 * ```
 */
export function MediaCard({
  src,
  svgContent,
  svgType = 'image',
  alt = '',
  mediaType = 'image',
  title,
  caption,
  objectFit = 'cover',
  overlay,
  asBackground = false,
  fallbackImage,
  onError,
  children,
  padding = 'none',
  className = '',
  ...containerProps
}: MediaCardProps) {
  const [imageError, setImageError] = useState(false);
  const paddingClass = {
    compact: 'slide-card-compact',
    default: '',
    spacious: 'slide-card-spacious',
    none: 'slide-card-flush',
  }[padding];

  // Handle image load error
  const handleImageError = (e: React.SyntheticEvent<HTMLImageElement, Event>) => {
    if (fallbackImage && !imageError) {
      setImageError(true);
      e.currentTarget.src = fallbackImage;
    }
    if (onError) {
      onError(new Error(`Failed to load image: ${src}`));
    }
  };

  // SVG rendering logic
  if (mediaType === 'svg' && svgContent) {
    if (svgType === 'interactive') {
      // Interactive mode - render SVG directly in DOM
      return (
        <CardContainer {...containerProps} className={clsx('relative overflow-hidden', paddingClass, className)}>
          <div
            className="w-full h-full"
            dangerouslySetInnerHTML={{ __html: svgContent }}
            role="img"
            aria-label={alt}
          />

          {/* Title Overlay */}
          {title && (
            <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent p-6">
              <h3 className="text-white text-2xl font-semibold">{title}</h3>
            </div>
          )}

          {/* Custom Overlay */}
          {overlay && (
            <div className="absolute inset-0 flex items-center justify-center">
              {overlay}
            </div>
          )}

          {/* Caption */}
          {caption && (
            <div className="absolute bottom-0 left-0 right-0 bg-slidey-background/95 p-4 border-t border-slidey-border">
              <div className="text-sm text-slidey-muted-foreground">{caption}</div>
            </div>
          )}
        </CardContainer>
      );
    } else {
      // Image mode - render as data URI
      const dataUri = `data:image/svg+xml;utf8,${encodeURIComponent(svgContent)}`;
      return (
        <CardContainer {...containerProps} className={clsx('relative overflow-hidden', paddingClass, className)}>
          <img
            src={dataUri}
            alt={alt}
            className={clsx('w-full h-full', objectFitClasses[objectFit])}
            loading="lazy"
          />

          {/* Title Overlay */}
          {title && (
            <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent p-6">
              <h3 className="text-white text-2xl font-semibold">{title}</h3>
            </div>
          )}

          {/* Custom Overlay */}
          {overlay && (
            <div className="absolute inset-0 flex items-center justify-center">
              {overlay}
            </div>
          )}

          {/* Caption */}
          {caption && (
            <div className="absolute bottom-0 left-0 right-0 bg-slidey-background/95 p-4 border-t border-slidey-border">
              <div className="text-sm text-slidey-muted-foreground">{caption}</div>
            </div>
          )}
        </CardContainer>
      );
    }
  }

  if (asBackground) {
    // Use media as background with content overlay
    return (
      <CardContainer
        {...containerProps}
        backgroundImage={src}
        className={clsx('relative flex items-center justify-center', paddingClass, className)}
      >
        {overlay && (
          <div className="absolute inset-0 flex items-center justify-center p-8">
            {overlay}
          </div>
        )}
        {children && <div className="relative z-10">{children}</div>}
      </CardContainer>
    );
  }

  return (
    <CardContainer {...containerProps} className={clsx('relative overflow-hidden', paddingClass, className)}>
      {/* Media Content */}
      <div className="relative w-full h-full">
        {mediaType === 'video' ? (
          <video
            src={src}
            className={clsx('w-full h-full', objectFitClasses[objectFit])}
            controls
            playsInline
          >
            <track kind="captions" />
          </video>
        ) : (
          <img
            src={src}
            alt={alt}
            className={clsx('w-full h-full', objectFitClasses[objectFit])}
            loading="lazy"
            onError={handleImageError}
          />
        )}

        {/* Title Overlay */}
        {title && (
          <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent p-6">
            <h3 className="text-white text-2xl font-semibold">{title}</h3>
          </div>
        )}

        {/* Custom Overlay */}
        {overlay && (
          <div className="absolute inset-0 flex items-center justify-center">
            {overlay}
          </div>
        )}
      </div>

      {/* Caption */}
      {caption && (
        <div className="absolute bottom-0 left-0 right-0 bg-slidey-background/95 p-4 border-t border-slidey-border">
          <div className="text-sm text-slidey-muted-foreground">{caption}</div>
        </div>
      )}
    </CardContainer>
  );
}

// packages/slideyui-svelte/src/lib/components/MediaCard.svelte
<script lang="ts">
	/**
	 * MediaCard Component
	 * Image, video, and SVG-focused presentation card
	 * Optimized for visual content with optional overlays and captions
	 */

	import CardContainer from './CardContainer.svelte';
	import type { CardPadding } from '../types';

	export let src: string | undefined = undefined;
	export let svgContent: string | undefined = undefined;
	export let svgType: 'image' | 'interactive' = 'image';
	export let alt: string = '';
	export let mediaType: 'image' | 'video' | 'svg' = 'image';
	export let title: string | undefined = undefined;
	export let caption: string | undefined = undefined;
	export let asBackground: boolean = false;
	export let fallbackImage: string | undefined = undefined;
	export let onError: ((error: Error) => void) | undefined = undefined;
	export let padding: CardPadding = 'none';
	export let aspectRatio: '16/9' | '4/3' | '1/1' | '3/2' | 'auto' = '16/9';
	export let mode: 'preview' | 'thumbnail' | 'full' = 'preview';
	export let bordered: boolean = true;
	export let shadow: boolean = true;
	export let interactive: boolean = false;
	export let cardId: string | undefined = undefined;
	export let cardState: 'generating' | 'selected' | 'error' | 'complete' | undefined = undefined;

	let className: string = '';
	export { className as class };

	const paddingClass = {
		compact: 'slide-card-compact',
		default: '',
		spacious: 'slide-card-spacious',
		none: 'slide-card-flush',
	}[padding];

	let imageError = false;

	// Handle image load error
	function handleImageError(e: Event) {
		if (fallbackImage && !imageError && e.target instanceof HTMLImageElement) {
			imageError = true;
			e.target.src = fallbackImage;
		}
		if (onError) {
			onError(new Error(`Failed to load image: ${src}`));
		}
	}

	// Create SVG data URI for image mode
	let svgDataUri = '';
	$: if (mediaType === 'svg' && svgContent && svgType === 'image') {
		svgDataUri = `data:image/svg+xml;utf8,${encodeURIComponent(svgContent)}`;
	}
</script>

<!-- SVG Rendering (Interactive Mode) -->
{#if mediaType === 'svg' && svgContent && svgType === 'interactive'}
	<CardContainer
		{aspectRatio}
		{mode}
		{bordered}
		{shadow}
		{interactive}
		{cardId}
		{cardState}
		class="relative overflow-hidden {paddingClass} {className}"
	>
		<div class="w-full h-full" role="img" aria-label={alt}>
			{@html svgContent}
		</div>

		{#if title}
			<div class="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent p-6">
				<h3 class="text-white text-2xl font-semibold">{title}</h3>
			</div>
		{/if}

		{#if $$slots.overlay}
			<div class="absolute inset-0 flex items-center justify-center">
				<slot name="overlay" />
			</div>
		{/if}

		{#if caption}
			<div class="absolute bottom-0 left-0 right-0 bg-slidey-background/95 p-4 border-t border-slidey-border">
				<div class="text-sm text-slidey-muted-foreground">{caption}</div>
			</div>
		{/if}
	</CardContainer>

<!-- SVG Rendering (Image Mode) -->
{:else if mediaType === 'svg' && svgContent && svgType === 'image'}
	<CardContainer
		{aspectRatio}
		{mode}
		{bordered}
		{shadow}
		{interactive}
		{cardId}
		{cardState}
		class="relative overflow-hidden {paddingClass} {className}"
	>
		<img src={svgDataUri} {alt} class="w-full h-full object-contain" loading="lazy" />

		{#if title}
			<div class="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent p-6">
				<h3 class="text-white text-2xl font-semibold">{title}</h3>
			</div>
		{/if}

		{#if $$slots.overlay}
			<div class="absolute inset-0 flex items-center justify-center">
				<slot name="overlay" />
			</div>
		{/if}

		{#if caption}
			<div class="absolute bottom-0 left-0 right-0 bg-slidey-background/95 p-4 border-t border-slidey-border">
				<div class="text-sm text-slidey-muted-foreground">{caption}</div>
			</div>
		{/if}
	</CardContainer>

<!-- Background Mode -->
{:else if asBackground}
	<CardContainer
		{aspectRatio}
		{mode}
		{bordered}
		{shadow}
		{interactive}
		{cardId}
		{cardState}
		backgroundImage={src}
		class="relative {paddingClass} {className}"
	>
		<div class="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent"></div>
		<div class="relative z-10 p-8 flex flex-col justify-end h-full">
			{#if title}
				<h3 class="text-2xl font-bold mb-2 text-white">{title}</h3>
			{/if}
			<slot />
		</div>

		{#if $$slots.overlay}
			<div class="absolute inset-0 flex items-center justify-center p-8">
				<slot name="overlay" />
			</div>
		{/if}
	</CardContainer>

<!-- Standard Image/Video Mode -->
{:else}
	<CardContainer
		{aspectRatio}
		{mode}
		{bordered}
		{shadow}
		{interactive}
		{cardId}
		{cardState}
		class="relative overflow-hidden {paddingClass} {className}"
	>
		<div class="relative w-full h-full">
			{#if mediaType === 'video'}
				<video {src} class="w-full h-full object-cover" controls playsinline>
					<track kind="captions" />
				</video>
			{:else}
				<img {src} {alt} class="w-full h-full object-cover" loading="lazy" on:error={handleImageError} />
			{/if}

			{#if title}
				<div class="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent p-6">
					<h3 class="text-white text-2xl font-semibold">{title}</h3>
				</div>
			{/if}

			{#if $$slots.overlay}
				<div class="absolute inset-0 flex items-center justify-center">
					<slot name="overlay" />
				</div>
			{/if}
		</div>

		{#if caption}
			<div class="absolute bottom-0 left-0 right-0 bg-slidey-background/95 p-4 border-t border-slidey-border">
				<div class="text-sm text-slidey-muted-foreground">{caption}</div>
			</div>
		{/if}
	</CardContainer>
{/if}
