// packages/slideyui-react/src/components/cards/QuoteCard.tsx
/**
 * QuoteCard Component
 * Pull quotes and testimonials card
 * Presentation-optimized for impactful quotes
 */

import { QuoteCardProps } from '../../types';
import { CardContainer } from './CardContainer';
import clsx from 'clsx';

/**
 * Quote-focused card for testimonials and pull quotes
 *
 * @example
 * ```tsx
 * // Simple quote
 * <QuoteCard
 *   quote="This changed everything for our team."
 *   author="Jane Doe"
 *   source="CEO, Acme Corp"
 * />
 *
 * // Testimonial with avatar
 * <QuoteCard
 *   variant="testimonial"
 *   quote="The best presentation tool we've ever used."
 *   author="John Smith"
 *   source="Product Manager"
 *   avatar="/avatars/john.jpg"
 * />
 * ```
 */
export function QuoteCard({
  quote,
  author,
  source,
  avatar,
  variant = 'default',
  padding = 'spacious',
  className = '',
  ...containerProps
}: QuoteCardProps) {
  const paddingClass = {
    compact: 'slide-card-compact',
    default: '',
    spacious: 'slide-card-spacious',
    none: 'slide-card-flush',
  }[padding];

  return (
    <CardContainer
      {...containerProps}
      className={clsx(
        'flex flex-col justify-between card-quote-card',
        paddingClass,
        variant === 'minimal' && 'border-none shadow-none',
        className
      )}
    >
      {/* Quote Mark (for non-minimal variants) */}
      {variant !== 'minimal' && (
        <div className="text-6xl text-slidey-accent/20 leading-none mb-4">
          &ldquo;
        </div>
      )}

      {/* Quote Text */}
      <div className="flex-1 mb-6">
        <blockquote
          className={clsx(
            'text-slidey-foreground',
            variant === 'large' ? 'text-3xl' : 'text-2xl',
            variant === 'minimal' && 'italic border-l-4 border-slidey-accent pl-4'
          )}
        >
          {quote}
        </blockquote>
      </div>

      {/* Author Attribution */}
      {(author || source || avatar) && (
        <div className="flex items-center gap-4 mt-auto">
          {avatar && (
            <img
              src={avatar}
              alt={author || 'Author'}
              className="w-12 h-12 rounded-full object-cover"
            />
          )}
          <div>
            {author && (
              <div
                className={clsx(
                  'font-semibold text-slidey-foreground',
                  variant === 'large' ? 'text-xl' : 'text-lg'
                )}
              >
                {author}
              </div>
            )}
            {source && (
              <div className="text-sm text-slidey-muted-foreground">
                {source}
              </div>
            )}
          </div>
        </div>
      )}
    </CardContainer>
  );
}

// packages/slideyui-svelte/src/lib/components/QuoteCard.svelte
<script lang="ts">
	/**
	 * QuoteCard Component
	 * Pull quotes and testimonials card
	 * Presentation-optimized for impactful quotes
	 *
	 * @example
	 * ```svelte
	 * // Simple quote
	 * <QuoteCard
	 *   quote="This changed everything for our team."
	 *   author="Jane Doe"
	 *   source="CEO, Acme Corp"
	 * />
	 *
	 * // Testimonial with avatar
	 * <QuoteCard
	 *   variant="testimonial"
	 *   quote="The best presentation tool we've ever used."
	 *   author="John Smith"
	 *   source="Product Manager"
	 *   avatar="/avatars/john.jpg"
	 * />
	 * ```
	 */

	import CardContainer from './CardContainer.svelte';
	import type { CardPadding } from '../types';

	export let quote: string;
	export let author: string | undefined = undefined;
	export let source: string | undefined = undefined;
	export let avatar: string | undefined = undefined;
	export let variant: 'default' | 'large' | 'minimal' | 'testimonial' = 'default';
	export let padding: CardPadding = 'spacious';
	export let aspectRatio: '16/9' | '4/3' | '1/1' | '3/2' | 'auto' = '16/9';
	export let mode: 'preview' | 'thumbnail' | 'full' = 'preview';
	export let bordered: boolean = true;
	export let shadow: boolean = true;
	export let interactive: boolean = false;
	export let backgroundColor: string | undefined = undefined;
	export let backgroundImage: string | undefined = undefined;
	export let cardId: string | undefined = undefined;
	export let cardState: 'generating' | 'selected' | 'error' | 'complete' | undefined = undefined;

	let className: string = '';
	export { className as class };

	const paddingClass = {
		compact: 'slide-card-compact',
		default: '',
		spacious: 'slide-card-spacious',
		none: 'slide-card-flush',
	}[padding];

	$$restProps; // Allow passing through other props
</script>

<CardContainer
	{aspectRatio}
	{mode}
	{bordered}
	{shadow}
	{interactive}
	{backgroundColor}
	{backgroundImage}
	{cardId}
	{cardState}
	class="flex flex-col justify-between card-quote-card {paddingClass} {variant ===
	'minimal'
		? 'border-none shadow-none'
		: ''} {className}"
>
	<!-- Quote Mark (for non-minimal variants) -->
	{#if variant !== 'minimal'}
		<div class="text-6xl text-slidey-accent/20 leading-none mb-4">&ldquo;</div>
	{/if}

	<!-- Quote Text -->
	<div class="flex-1 mb-6">
		<blockquote
			class="text-slidey-foreground {variant === 'large'
				? 'text-3xl'
				: 'text-2xl'} {variant === 'minimal' ? 'italic border-l-4 border-slidey-accent pl-4' : ''}"
		>
			{quote}
		</blockquote>
	</div>

	<!-- Author Attribution -->
	{#if author || source || avatar}
		<div class="flex items-center gap-4 mt-auto">
			{#if avatar}
				<img src={avatar} alt={author || 'Author'} class="w-12 h-12 rounded-full object-cover" />
			{/if}
			<div>
				{#if author}
					<div
						class="font-semibold text-slidey-foreground {variant === 'large'
							? 'text-xl'
							: 'text-lg'}"
					>
						{author}
					</div>
				{/if}
				{#if source}
					<div class="text-sm text-slidey-muted-foreground">
						{source}
					</div>
				{/if}
			</div>
		</div>
	{/if}
</CardContainer>
