// packages/slideyui-react/src/components/SlideNumber.tsx
/**
 * SlideNumber Component
 * Slide number display indicator
 */

import { SlideNumberProps } from '../types';
import { usePresentationContext } from './Presentation';

/**
 * Slide number indicator showing current slide position
 *
 * @example
 * ```tsx
 * <SlideNumber position="bottom-right" format="fraction" />
 * ```
 */
export function SlideNumber({
  position = 'bottom-right',
  format = 'fraction',
  className = '',
}: SlideNumberProps) {
  const { currentCard, totalCards } = usePresentationContext();
  const currentSlide = currentCard;
  const totalSlides = totalCards;

  const displayNumber = format === 'fraction'
    ? `${currentSlide + 1} / ${totalSlides}`
    : `${currentSlide + 1}`;

  return (
    <div
      className={`presentation-number presentation-number-${position} ${className}`}
      aria-label={`Slide ${currentSlide + 1} of ${totalSlides}`}
    >
      {displayNumber}
    </div>
  );
}

// packages/slideyui-svelte/src/lib/components/SlideNumber.svelte
<!--
  SlideNumber Component
  Slide number display indicator
-->

<script lang="ts">
  import { getPresentationContext } from '../stores/presentation';

  /**
   * Position
   */
  export let position: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left' = 'bottom-right';

  /**
   * Show format (e.g., "1/10" or just "1")
   */
  export let format: 'fraction' | 'current' = 'fraction';

  /**
   * Additional CSS classes
   */
  let className: string = '';
  export { className as class };

  // Get presentation context
  const presentationContext = getPresentationContext();

  const currentSlide = $derived(presentationContext?.state.currentCard ?? 0);
  const totalSlides = $derived(presentationContext?.state.totalCards ?? 0);

  const displayNumber = $derived(
    format === 'fraction'
      ? `${currentSlide + 1} / ${totalSlides}`
      : `${currentSlide + 1}`
  );
</script>

<!--
  Slide number indicator showing current slide position

  @example
  ```svelte
  <SlideNumber position="bottom-right" format="fraction" />
  ```
-->

<div
  class="slide-number slide-number-{position} {className}"
  aria-label="Slide {currentSlide + 1} of {totalSlides}"
>
  {displayNumber}
</div>
